# Generated by .github/workflows/release.yml in gulshanAI/cloud_code_terminal.
# Edit packaging/homebrew/tether.rb.tmpl there, not this file.
class Tether < Formula
  desc "Your dev machine in your pocket: files, terminals, git and previews from your phone"
  homepage "https://ter.soiltonenatural.com"
  version "0.5.0"

  on_macos do
    on_arm do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.5.0/tether_0.5.0_darwin_arm64.tar.gz"
      sha256 "2a5160cbe250cf65932b7a6fe9d5618be8840c26dc149200c7fc9171f9ed5f71"
    end
    on_intel do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.5.0/tether_0.5.0_darwin_amd64.tar.gz"
      sha256 "d673fd19ad43a19c4174658e7998b87dfb13e930a7553c4c6b5a2bd16a0233da"
    end
  end

  on_linux do
    on_arm do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.5.0/tether_0.5.0_linux_arm64.tar.gz"
      sha256 "ba9014ff9eb8026e8484f1f12c7dfb444d24b8c010a49db72b5ac0ee0c141fd2"
    end
    on_intel do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.5.0/tether_0.5.0_linux_amd64.tar.gz"
      sha256 "39dde4a301704a30662f9a497dafdb55ed071bab31383e47202d6b704b3197b3"
    end
  end

  # The public link comes from a Cloudflare quick tunnel.
  depends_on "cloudflared"

  def install
    bin.install "tether"
  end

  def caveats
    <<~EOS
      Start Tether in the background (it also starts again at login):
        tether start

      It prints a link and a QR code that open the Tether app for this
      machine: https://ter.soiltonenatural.com

      After `brew upgrade tether`, run `tether restart`.
      Other commands: tether status | logs | stop | help
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tether version")
    assert_match "tether start", shell_output("#{bin}/tether help 2>&1")
  end
end
