# Generated by .github/workflows/release.yml in gulshanAI/cloud_code_terminal.
# Edit packaging/homebrew/tether.rb.tmpl there, not this file.
class Tether < Formula
  desc "Your dev machine in your pocket: files, terminals, git and previews from your phone"
  homepage "https://ter.soiltonenatural.com"
  version "0.6.0"

  on_macos do
    on_arm do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.6.0/tether_0.6.0_darwin_arm64.tar.gz"
      sha256 "76edb31a1f997f47ce035f2bf837f2c3a508d086010288e62ad658372add9ac5"
    end
    on_intel do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.6.0/tether_0.6.0_darwin_amd64.tar.gz"
      sha256 "981a314b18286c5a21a117e029e8a40fcf4310691c95aafccd55728a37255670"
    end
  end

  on_linux do
    on_arm do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.6.0/tether_0.6.0_linux_arm64.tar.gz"
      sha256 "5a0a9224fef8906439e951016952fe8ce95bf167b57d272352820b1ab5a8809f"
    end
    on_intel do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.6.0/tether_0.6.0_linux_amd64.tar.gz"
      sha256 "3b312385380d756cc9450c0486451833b1bbad52e7cdcfee2ee6f5dc76d7b378"
    end
  end

  # The public link comes from a Cloudflare quick tunnel.
  depends_on "cloudflared"

  def install
    bin.install "tether"
  end

  def caveats
    <<~EOS
      Start Tether in the background (it also starts again at login):
        tether start

      It prints a link and a QR code that open the Tether app for this
      machine: https://ter.soiltonenatural.com

      After `brew upgrade tether`, run `tether restart`.
      Other commands: tether status | logs | stop | help
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tether version")
    assert_match "tether start", shell_output("#{bin}/tether help 2>&1")
  end
end
