# Generated by .github/workflows/release.yml in gulshanAI/cloud_code_terminal.
# Edit packaging/homebrew/tether.rb.tmpl there, not this file.
class Tether < Formula
  desc "Your dev machine in your pocket: files, terminals, git and previews from your phone"
  homepage "https://ter.soiltonenatural.com"
  version "0.4.1"

  on_macos do
    on_arm do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.4.1/tether_0.4.1_darwin_arm64.tar.gz"
      sha256 "7c3efe93c353fd1ebdf0fba3119e97d81a14ca2e1681b37560266ca9edd26028"
    end
    on_intel do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.4.1/tether_0.4.1_darwin_amd64.tar.gz"
      sha256 "a874152283413e69e989a3955537255701ad56f924d8714cdec6652b44820b5b"
    end
  end

  on_linux do
    on_arm do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.4.1/tether_0.4.1_linux_arm64.tar.gz"
      sha256 "f07d91c4fcea460d29bc3f6bdb228ffcf9e439c360a161968fd66a3de52003b6"
    end
    on_intel do
      url "https://gulshanai-tether-releases.s3.ap-south-1.amazonaws.com/v0.4.1/tether_0.4.1_linux_amd64.tar.gz"
      sha256 "c8da0276c84e266fe0b4ebc6dec10c01e311ad9b50d267cdf13301cb6fa15b7a"
    end
  end

  # The public link comes from a Cloudflare quick tunnel.
  depends_on "cloudflared"

  def install
    bin.install "tether"
  end

  def caveats
    <<~EOS
      Start Tether in the background (it also starts again at login):
        tether start

      It prints a link and a QR code that open the Tether app for this
      machine: https://ter.soiltonenatural.com

      After `brew upgrade tether`, run `tether restart`.
      Other commands: tether status | logs | stop | help
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/tether version")
    assert_match "tether start", shell_output("#{bin}/tether help 2>&1")
  end
end
